name: CI

on: push

jobs:
  generate-matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-latest
    outputs:
      recipes: ${{ steps.set-matrix.outputs.recipes }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - run: node ./get-checks.js
        id: set-matrix

  run-task:
    name: ${{ matrix.recipes.doc }}
    runs-on: ubuntu-latest
    needs: [generate-matrix]
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix: ${{fromJSON(needs.generate-matrix.outputs.recipes)}}

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - run: just --justfile ${{ matrix.recipes.file }} ${{ matrix.recipes.name }}
